 /* */

 // ==========  PRODUCTS ==========

 const productList = [{
         img: '../resources/shop/ring/celtic1.png',
         img2: '../resources/shop/ring/celtic2.png',
         img3: '../resources/shop/ring/celtic3.png',
         type: 'RING',
         name: 'Anillo Celta',
         description: 'Anillo celta imbuido con un poder maligno antiguo, aun se desconoce todo su potencial mas alla de notar un desgaste fisico al portarlo',
         curse: true,
         blessing: false,
         conditionDesc: 'Cansancio fisico',
         price: 50,
         stock: true,
     },
     {
         img: '../resources/shop/ring/egypt1.png',
         img2: '../resources/shop/ring/egypt2.png',
         img3: '../resources/shop/ring/egypt3.png',
         type: 'RING',
         name: 'Anillo Egipcio',
         description: 'Anillo egipcio fabricado en oro, basado en antiguos planos encontrados en una exploracion extra-oficial a la piramide de Giza, el mismo dota de una gran sabiduria a quien lo porte',
         curse: false,
         blessing: true,
         conditionDesc: 'Sabiduria',
         price: 1200,
         stock: true,
     },
     {
         img: '../resources/shop/ring/moth1.png',
         img2: '../resources/shop/ring/moth2.png',
         img3: '../resources/shop/ring/moth3.png',
         type: 'RING',
         name: 'Anillo del culto a Mother',
         description: 'Anillo bendecido por uno de los altos sacerdotes del culto a Mother, sus efectos aun son desconocidos, pero se dice que ofrece a su portador una perdida temporal del control corporal, entrando en un estado de trance',
         curse: true,
         blessing: false,
         conditionDesc: 'Zombificacion, Control mental',
         price: 700,
         stock: true,
     },
     {
         img: '../resources/shop/ring/nebula1.png',
         img2: '../resources/shop/ring/nebula2.png',
         img3: '../resources/shop/ring/nebula3.png',
         type: 'RING',
         name: 'Anillo Estelar',
         description: 'Anillo fabricado con materiales que ingresaron a la Tierra hace milenios, el mismo ofrece un sentimiento de calma, el cual se compara a un viaje astral',
         curse: false,
         blessing: true,
         conditionDesc: 'Calma, Viaje astral',
         price: 2000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/piramid1.png',
         img2: '../resources/shop/ring/piramid2.png',
         img3: '../resources/shop/ring/piramid3.png',
         type: 'RING',
         name: 'Anillo Piramidal',
         description: 'Anillo dotado de un onix en forma piramidal, el mismo no fue manipulado fisicamente por nadie, ya que su forma se obtuvo por medio del intercambio equivalente, el cual dota a su portador del control total de sus emociones',
         curse: false,
         blessing: true,
         conditionDesc: 'Autocontrol',
         price: 3500,
         stock: true,
     },
     {
         img: '../resources/shop/ring/symbol1.png',
         img2: '../resources/shop/ring/symbol2.png',
         img3: '../resources/shop/ring/symbol3.png',
         type: 'RING',
         name: 'Anillo de la demecia',
         description: 'Anillo dotado de un poder incontrolable, el mismo genera un sonido constante a una baja frecuencia, siendo este el causante de diferentes molestias hasta llegar a la completa demencia',
         curse: true,
         blessing: false,
         conditionDesc: 'Demencia, Ateracion',
         price: 12000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/tooth1.png',
         img2: '../resources/shop/ring/tooth2.png',
         img3: '../resources/shop/ring/tooth3.png',
         type: 'RING',
         name: 'Anillo de la bestia',
         description: 'Anillo dotado del poder del familiar, el portador recibe la visita de un familiar canino que lo ayuda en todo momento que lo necesite a cambio de afecto y ofrendas menores (comida, juguetes, entre otros)',
         curse: false,
         blessing: true,
         conditionDesc: 'Familiar, Invocacion',
         price: 16750,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     },
     {
         img: '../resources/shop/ring/celtic2.png',
         img2: ,
         img3: ,
         type: 'RING',
         name: 'AXE',
         description: 'Old axe',
         curse: true,
         blessing: false,
         conditionDesc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic, veritatis!',
         price: 1000,
         stock: true,
     }
 ];

 // ==========  CLASS FOR PRODUCTS ==========
 class ProdToCart {
     constructor(getObjImg, getObjName, getObjCurse, getObjBlessing, getObjCondDesc, getObjPrice) {
         this.img = getObjImg;
         this.name = getObjName;
         this.curse = getObjCurse;
         this.blessing = getObjBlessing;
         this.conditionDesc = getObjCondDesc;
         this.price = getObjPrice;
     }
 }

 let objectsToCart = [];

 let cartForTab = {};